### ISSUE TITLE
Vehicle still on the flatbed

### ISSUE THREAD

**Issue by jeffin86** [V4M0N0S/altv-flatbed#1]
Hi dude ! 

On my server we try to use your script but everytime we unlock the vehicle, its still on the flatbed :/ Do u have a solve on it ?

**Comment by V4M0N0S** [comment]
Hey, i currently not developing alt:V stuff, but im pretty sure there are some changes in the current version. 
This script was for alt:V 7.3, so you need to update some stuff.
